theme: jekyll-theme-minimal
logo: https://media.licdn.com/dms/image/C5616AQEg_0mz2EYYTQ/profile-displaybackgroundimage-shrink_350_1400/0?e=1580947200&v=beta&t=Mnr_BZjK9vfDJB62Ef1CgATycgP2fLFacmIk3DkZXgI
title: "Introduction to Bioinformatics"
