---
title: "Class 6 R Functions"
author: "Yu Zhang"
date: "2019/10/18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
read.table("test1.txt",sep = ",")
read.table("test2.txt",sep = "$")
read.table("test3.txt", sep = "")
```


```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y
}
add(2)
add(c(1,2),2)
add(nchar("2sd"))
x <- c(1,3,4)
range(x)
```


```{r}
rescale <- function(x, na.rm=TRUE, plot=FALSE) {
 if(na.rm) {
 rng <-range(x, na.rm=TRUE)
 } else {
 rng <-range(x)
 }
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 return(answer) #skips the rest of the calculations
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
}
```
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
#par(mfrow = c(1,3))
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
#points(s2.b, typ = "l", col = "blue")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```
```{r}
#library(bio3d)
prostr <- function(x, chain_name = "A", elety_name = "CA", yl = "Bfactor", atom_col = "b"){
  s <- read.pdb(x)
  s.chain <- trim.pdb(s, chain = chain_name, elety = elety_name)
  s.atom <- s.chain$atom[,atom_col]
  plotb3(s.atom, sse=s.chain, typ="l", ylab = yl)
}
prostr("4AKE")
```




